CLASS zcl_06_storage_sar DEFINITION INHERITING FROM zcl_05_plant_sar
  PUBLIC
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_06_storage_sar IMPLEMENTATION.
ENDCLASS.
